# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install pip pipx
      run: |
        python -m pip install --upgrade pip
        pip install pipx
    - name: Install poetry 
        python -m pipx install poetry
    - name: Install project dependencies 
        poetry update
        poetry install
    - name: Build and publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ PYPI_TOCKEN }}
      run: |
        poetry publish
